# Generated by Django 5.2.15 on 2026-07-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_role', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('MANAGER', 'Manager'), ('CLIENT_USER', 'Client user')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('user', 'client'), name='unique_user_client_membership')],
            },
        ),
    ]
