# Generated by Django 5.2.15 on 2026-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=40, unique=True)),
                ('nvd_description', models.TextField(blank=True, null=True)),
                ('nvd_cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nvd_cvss_vector', models.CharField(blank=True, max_length=255, null=True)),
                ('cwe_ids', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('kev_listed', models.BooleanField(default=False)),
                ('kev_date_added', models.DateField(blank=True, null=True)),
                ('epss_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('epss_percentile', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('source_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='FAILED', max_length=20)),
                ('last_safe_error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cve_id'],
                'indexes': [models.Index(fields=['cve_id'], name='intelligenc_cve_id_89d733_idx')],
            },
        ),
    ]
