import { Alert, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material';
import { formatDateTime } from '../../utils/formatters';

function valueOrDash(value) {
  return value === null || value === undefined || value === '' ? '-' : value;
}

export default function IntelligencePanel({ finding, intelligence, loading, error, canEdit, onRefresh }) {
  if (!finding?.cve_id) return null;
  return <Card><CardContent><Stack spacing={2}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} justifyContent="space-between"><div><Typography variant="h6">CVE intelligence</Typography><Typography color="text.secondary">Priority is a decision-support indicator, not a replacement for professional risk assessment.</Typography></div>{canEdit ? <Button variant="outlined" onClick={onRefresh} disabled={loading}>{loading ? 'Refreshing...' : 'Refresh intelligence'}</Button> : null}</Stack>{error ? <Alert severity="error">{error}</Alert> : null}<Grid container spacing={2}><Grid item xs={12} sm={3}><Typography variant="caption" color="text.secondary">CVE</Typography><Typography>{finding.cve_id}</Typography></Grid><Grid item xs={12} sm={3}><Typography variant="caption" color="text.secondary">NVD CVSS</Typography><Typography>{valueOrDash(intelligence?.nvd_cvss_score)}</Typography></Grid><Grid item xs={12} sm={3}><Typography variant="caption" color="text.secondary">CISA KEV</Typography><Typography>{intelligence?.kev_listed ? 'Listed' : 'Not listed'}</Typography></Grid><Grid item xs={12} sm={3}><Typography variant="caption" color="text.secondary">EPSS</Typography><Typography>{intelligence?.epss_score ? `${intelligence.epss_score} (${intelligence.epss_percentile ?? '-'} percentile)` : '-'}</Typography></Grid><Grid item xs={12} sm={3}><Typography variant="caption" color="text.secondary">Priority</Typography><br />{finding.priority_label ? <Chip label={`${finding.priority_label} ${finding.priority_score ?? ''}`} color={finding.priority_label === 'URGENT' ? 'error' : 'warning'} size="small" /> : <Typography>-</Typography>}</Grid><Grid item xs={12} sm={9}><Typography variant="caption" color="text.secondary">Reason</Typography><Typography>{finding.priority_reason || 'Refresh intelligence to compute priority.'}</Typography></Grid><Grid item xs={12}><Typography variant="caption" color="text.secondary">Last refreshed</Typography><Typography>{formatDateTime(intelligence?.source_retrieved_at)}</Typography></Grid></Grid></Stack></CardContent></Card>;
}
