# Generated by Django 5.2.15 on 2026-07-04 12:37

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0002_finding_priority_computed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=80)),
                ('content_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('REMEDIATION', 'Remediation')], default='REMEDIATION', max_length=30)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='remediation-v1', max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_artifacts', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artifacts', to='findings.finding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('embedding_model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='AIArtifactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('similarity', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('excerpt', models.CharField(max_length=500)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ai.aiartifact')),
                ('knowledge_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_sources', to='ai.knowledgechunk')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('artifact', 'knowledge_chunk'), name='unique_ai_artifact_source_chunk')],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index', 'content_hash'), name='unique_knowledge_chunk_content'),
        ),
    ]
