# Generated by Django 5.2.15 on 2026-07-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPORT_CREATED', 'Import created'), ('OBSERVATION_TRIAGED', 'Observation triaged'), ('OBSERVATION_PROMOTED', 'Observation promoted'), ('FINDING_UPDATED', 'Finding updated')], max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='assessments.assessment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenancy.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='audit_audit_client__7338ba_idx'), models.Index(fields=['assessment', '-created_at'], name='audit_audit_assessm_896532_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='audit_audit_entity__d357fe_idx')],
            },
        ),
    ]
