# Generated by Django 5.2.15 on 2026-07-06 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('audit', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='safe_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SCAN_IMPORT_CREATED', 'Scan import created'), ('OBSERVATION_TRIAGED', 'Observation triaged'), ('OBSERVATION_PROMOTED', 'Observation promoted'), ('FINDING_CREATED', 'Finding created'), ('FINDING_UPDATED', 'Finding updated'), ('FINDING_STATUS_CHANGED', 'Finding status changed'), ('FINDING_OWNER_CHANGED', 'Finding owner changed'), ('FINDING_DUE_DATE_CHANGED', 'Finding due date changed'), ('FINDING_RISK_ACCEPTED', 'Finding risk accepted'), ('FINDING_REOPENED', 'Finding reopened'), ('FINDING_CLOSED', 'Finding closed'), ('INTELLIGENCE_REFRESHED', 'Intelligence refreshed'), ('AI_REMEDIATION_DRAFT_GENERATED', 'AI remediation draft generated'), ('IMPORT_CREATED', 'Import created')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client', 'entity_type', 'entity_id', '-created_at'], name='audit_audit_client__eafe48_idx'),
        ),
    ]
