# Generated by Django 5.2.15 on 2026-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_safe_metadata_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SCAN_IMPORT_CREATED', 'Scan import created'), ('IMPORT_PREVIEW_CREATED', 'Import preview created'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('OBSERVATION_TRIAGED', 'Observation triaged'), ('OBSERVATION_PROMOTED', 'Observation promoted'), ('FINDING_CREATED', 'Finding created'), ('FINDING_UPDATED', 'Finding updated'), ('FINDING_STATUS_CHANGED', 'Finding status changed'), ('FINDING_OWNER_CHANGED', 'Finding owner changed'), ('FINDING_DUE_DATE_CHANGED', 'Finding due date changed'), ('FINDING_RISK_ACCEPTED', 'Finding risk accepted'), ('FINDING_REOPENED', 'Finding reopened'), ('FINDING_CLOSED', 'Finding closed'), ('INTELLIGENCE_REFRESHED', 'Intelligence refreshed'), ('AI_REMEDIATION_DRAFT_GENERATED', 'AI remediation draft generated'), ('IMPORT_CREATED', 'Import created')], max_length=80),
        ),
    ]
