# Generated by Django 5.2.15 on 2026-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='priority_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_label',
            field=models.CharField(blank=True, choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='priority_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
