# Generated by Django 5.2.15 on 2026-07-06 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_finding_priority_computed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='risk_acceptance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='risk_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='risk_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_accepted_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='risk_review_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='validation_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('ACCEPTED_RISK', 'Accepted risk'), ('MITIGATED', 'Mitigated'), ('VALIDATION_PENDING', 'Validation pending'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
