# Generated by Django 5.2.15 on 2026-07-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('framework', models.CharField(choices=[('ISO_27001', 'ISO 27001'), ('NIST', 'NIST'), ('OWASP', 'OWASP'), ('NIS2', 'NIS2'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenancy.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('HOST', 'Host'), ('APPLICATION', 'Application'), ('API', 'API'), ('DATABASE', 'Database'), ('CLOUD_RESOURCE', 'Cloud resource'), ('OTHER', 'Other')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('base_url', models.URLField(blank=True)),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('TEST', 'Test'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('internet_exposed', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assessments.assessment')),
            ],
            options={
                'ordering': ['assessment__name', 'display_name', 'hostname', 'base_url'],
            },
        ),
    ]
