# Generated by Django 5.2.15 on 2026-07-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('findings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tool', models.CharField(choices=[('NMAP', 'Nmap'), ('ZAP', 'OWASP ZAP'), ('NESSUS', 'Nessus'), ('BURP', 'Burp Suite')], max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observations_created', models.PositiveIntegerField(default=0)),
                ('observations_updated', models.PositiveIntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_imports', to='assessments.assessment')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tool', models.CharField(choices=[('NMAP', 'Nmap'), ('ZAP', 'OWASP ZAP'), ('NESSUS', 'Nessus'), ('BURP', 'Burp Suite')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('scanner_plugin_id', models.CharField(blank=True, max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('triage_status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('FALSE_POSITIVE', 'False positive'), ('DUPLICATE', 'Duplicate'), ('ACCEPTED_RISK', 'Accepted risk'), ('PROMOTED', 'Promoted')], default='NEW', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('raw_severity', models.CharField(blank=True, max_length=80)),
                ('confidence', models.CharField(blank=True, max_length=80)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
                ('suggested_remediation', models.TextField(blank=True)),
                ('cve_ids', models.JSONField(blank=True, default=list)),
                ('cwe_ids', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('raw_location', models.CharField(blank=True, max_length=500)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_observations', to='assessments.assessment')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_observations', to='assessments.asset')),
                ('first_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_observations', to='imports.scanimport')),
                ('last_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_observations', to='imports.scanimport')),
            ],
            options={
                'ordering': ['-last_seen_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScanImportObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('REOBSERVED', 'Re-observed')], max_length=20)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('scan_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_observations', to='imports.scanimport')),
                ('scanner_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_links', to='imports.scannerobservation')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='findings.finding')),
                ('scanner_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_sources', to='imports.scannerobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scannerobservation',
            constraint=models.UniqueConstraint(fields=('assessment', 'fingerprint'), name='unique_observation_fingerprint_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='scanimportobservation',
            constraint=models.UniqueConstraint(fields=('scan_import', 'scanner_observation'), name='unique_observation_per_scan_import'),
        ),
        migrations.AddConstraint(
            model_name='findingsource',
            constraint=models.UniqueConstraint(fields=('finding', 'scanner_observation'), name='unique_finding_observation_source'),
        ),
    ]
