# Generated by Django 5.2.15 on 2026-07-02 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerobservation',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='imports.scannerobservation'),
        ),
        migrations.AddField(
            model_name='scannerobservation',
            name='triage_note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scannerobservation',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannerobservation',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
