# Generated by Django 5.2.15 on 2026-07-07 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('imports', '0002_scannerobservation_duplicate_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tool', models.CharField(choices=[('NMAP', 'Nmap'), ('ZAP', 'OWASP ZAP'), ('NESSUS', 'Nessus'), ('BURP', 'Burp Suite')], max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('parser_version', models.CharField(blank=True, max_length=80)),
                ('safe_observations', models.JSONField(blank=True, default=list)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_previews', to='assessments.assessment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_import_previews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_previews', to=settings.AUTH_USER_MODEL)),
                ('scan_import', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_preview', to='imports.scanimport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment', '-created_at'], name='imports_imp_assessm_368bf3_idx'), models.Index(fields=['created_by', '-created_at'], name='imports_imp_created_7bbada_idx')],
            },
        ),
    ]
